apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Tell Kustomize to render this chart
helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 1.5.2
    releaseName: mon-alloy
    namespace: monitoring
    # Point to your local values file
    valuesFile: values.yaml