# User-friendly parameters
loki:
  endpoint: "http://loki-gateway.monitoring.svc/loki/api/v1/push"

tempo:
  endpoint: "tempo.monitoring.svc:4317"

prometheus:
  writeEndpoint: "http://prom-stack-prometheus.monitoring.svc:9090/api/v1/write"

# Configuration for the Sub-Chart (Official Alloy)
alloy:
  alloy:
    configMap:
      create: false # Important: We will provide our own ConfigMap
      name: alloy-custom-config # Must match the name in our template
      key: config.river