apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - sealed-grafana-creds.yaml
  - sealed-grafana-oauth-keycloak-creds.yaml
  - ingress-route.yaml

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.5.8
    releaseName: mon-grafana
    namespace: monitoring
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml