---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth-keycloak-creds
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgC5DppV76V/1s8p4itcgvWkyu8o2W2OFmQNF3cMfngSn4k8czLuV3Kap33WVnl6ITfD1YAoR522Zt3giCg/txBShbcSoBc7UmWyo3Nd3k5SJXcrmU7hh4X2ylSqpKiTEevYFdilDNN6qTQZHTUa4WL2PF6qdvrpJ2rknlp02AP99c9sTFbYaoLJxk2xZffMXVO9jvK4i+fcD6512D9lvsroaVB/CgZPfubV3kUYIzIsJWEVbRcXCXaQJL5yTGK2Ft89KiJqN49JgfyhjiYeSw+z6vHLKDm8GaSzyp8t2Y9p1xRi0M16AvUHBRUbmnG7w1mKCURvlXqLIXq8iL2lT3bfISJ8SjhJb3kXJo9VgDTUx55ujhr8yJ7T2deGu7GRq0ie+9pkiCGmCo786+rl71D//vgyJCJ+1uOetUH5RQgFglPIIVkCGy9L5XtYR1boKQxBPBiFwOLFMZiYVKOwhxQEfLkb9B6HHzimfocEVE9NlFotG+3ztmQ9jVuoSei+DQEKZJyp+99NRAgDC/H2C1gio3Pi/ywahlbVHxH288U7Zv/OBJbSIRMZCQoErVqDAoJd9bEoP4I9zF4powmepnD+yDzmXloXb1NlrgBj2c1jEuBzyTbEpB0OxbD1OB8zQJEO2yx8B8GllhdUiJTzYSpwnkGjHdhICE1Le9csslx+Q2+E2Cy9FtnozvTyeICJKekxXauaOjNT
    client_secret: AgDzeXC43OnQQcWM9e0N5a6FmzeNyz2J2r5gLo21MJM7lP/fKFKZ6BWIaHfVlnginb+tpbuoiHJWreeL0hXx0kec4PJcrv4LFx8J1TUftomZ+V7edK1uDQhsCkmEMC4oA9QCPxMa12xmFPEa6TXLRRNx2YX0S3fmYk56YET+TYMy+c/Yt7r/bsuSiOo/faGh49EStVj6cySg9qmD6D4rXoDx6zlktow0SIotJmFLW2/8Qiw2gtc8ICsfL1JUM8O0Kzff1P4WrIxe7pIf4hUtoAi11XMDKone4vbqabZ773opRJVfFC+7HLp0oN6ocNlEFMrkIOJMNwI8iYE935g1PHa2V59/QL0kd5J6yxIPUMC30Km/FGGAwduFaaAT0A5zZwF8T0Icvyj7Auo2YGdrA9HZHT845mwtQ9F0A1bfUqT2qajJh2JKUy4O9HGZCAP1cUqfrr111epo/Z+0x8l/jEC8wFbBuGaJ5x6IWTA39abW4emdaGCchMVd9o6Hz+mrNl9/UQuC9pOcwSEcit1OQOw7nMAX/WIb8Jwwqb5yaZvdsyZDvouqAIKrqeoLsFL5vRX6bHr1ivNpAg9PXLW4U5XRJIG9QjqNXUsYVC2DzHJyyyD1QITHYflhE8F0Jx6rCluPy2phEZEcAiSWMbNFIIApBcMv8Ql4esaWCza6nT9+p5F3n4hlZ21JXo6BtwEouFuqaDK2OSmjtDsrJVg+6FSeLZ71QMS8jbb9imgVdFF7lw==
  template:
    metadata:
      name: grafana-oauth-keycloak-creds
      namespace: monitoring
