---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth-keycloak-creds
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgC+fn1WsLL4hlm0I/koBDt+BeAJVFQJWorHbiKWKkIkK95iCt0ZcXyHg454zcIRKv0+DztVpZyfEiCM25IJ2t1JqyQBXpPsvEGAKV24tbX5MLEvFeKL8A1u7l32nJ7OsW64RayZpqlR6rj4XQw/cHMdTTldGkkwS8gwuIjx3KqKxlBx9NVtZyqfbtrYj6p/xvAlkvsJlBPmChI+9iPByb224bO/+i5vHarMuKDPX9GhSdzQ5cAjB8cCr/YmzLJn+8vEWRbLmiKdu941ReMTwS7LWrzp1xSq/iNQpR+Eawv4M6P3hEuQ+uqg8M/dOKyfCN5JH7J66uc83lrnTdGjx6xfoROmATUvr9vNy3zj/4jVhQObrko53pzM6wrGmVRWlo8yRirlG6NnCk7bkvGfCQ8pPa4s8JTRp9VCgeTyxTEaxyjIsgncZs5FG4mlMjZ6ppKcgt7Zmx0hI0Wesp2SXDOb3kMug9X9zCcoI9dkWsqZ/Azt/9XuBxyCLGc0LXi2oqUUv0e1ZGHmlyQWIaT7aGe/AIP70y1hgrdPPNCPoeSHXDsrYlmIa0byRUgvrrx/CWakf8BeAMyRJx9lalm0DSXwgegvtEH0DKbGOaDvEbfc4zVod7JEjHeppSgghvqSdgRTC3xgzT0vitmzE8QYbmNZsWD/dJ7EQsU6mhOIpCTFG+QbpbanDWzUBf3wTeTCTCBsNRkGd41m
    client_secret: AgClYJmTFxIRCtSDHBz6AHZ7Q7GkpeK8+uO0jDg79o2Zav0+zlvtSDk5EN1LnEHL5dij6ip4Nb+6YFtTpMRcbzCJmYXHRgGfofXKoTG/GRAKIippKHzU/rTG7rkk+fc342kh9yiiqG0Yi+hqfKx+tOhgLoLjfP/DzK+nRxbHkUQYaal3FBul6sJefOHnA5s3JY0iiAjeBB0Rc/DNeMQ58QMRV5LfvE6Lk7bNCjKplXnTmJT6HnO965jretf6zovRIaJBYNBDL/UzHn6DrRnXKN9jbnth1bua9pyUr+qETMKg+IDkbi2Fhu8eUzPI/Pj8QTGtsloa9ozGSR8+Gnk7rmjzPGVVuDG7Ddx9B7zit526uvSEbeNIP6lMWnSSnM4xdOFEBJq8sehw/UbQvX9a74mgFoCCWKoE+3SV3hjnw+ZG60KAsoY7jK8wSP4YFuKovK4GB9S8rdts0+J6BCt3PnLclQLeJK7hjuaJqofVg1KolYZmssw4vYGLAId496eOCNRS8NzKX0/DZVIDgFcdbBoLDsYGrbVTm/JVsMxvuHli3khLpVeoP9CPP6eeQOyg5CqREMSxAxUwObUbq8KE3IVbNR3fdS8Q3CFYlsfxg7GPAagAQu1C7o8LN9qqgu84/VIHxTOPELHUzonFGY8pmuVshIDPHxSTTBCwHHBhhrTV798e18svVse4EuR5s9pAl+wyK0zzS5aU4hlZg9/TDPkb257n+Cm+qmBzcC2dB5062g==
  template:
    metadata:
      name: grafana-oauth-keycloak-creds
      namespace: monitoring
