---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAEXJWG/kSY2hMnFT8ceG2lm0x3AyoWlCyAh9w+qEtMVyeHYBlBGLlLxurRDwtAUc6FEdC7UKixZlsOWf+6UKKUlMn4tRbzfD+AvXyWHDu0B0GVNOGxhzqaLlEtNBFpPA5RlObYPnEyVtLrx5HTR+ktmFAlR0nB6HdJbGI5zWV9oAPIkRh7BxrPPa2X+OQxrX12hbrwXo+LcF+PKqMU4MjQQsNU30Pk1CholyV6SwPCg6w8jZ3rG4YeA2UiYYDUGbaVrZZU7HA8bj9ZJz4P0FHdsxsjo/U0eeUOP1S3s45aFFR+BNvUXT2F1mZTvuzmQRXTPmmxRKxyHVbLrpIadxrd/Ls8Do8yGGiXYBHD8sApGaiUXrj7jqaflcpIvfAiFXP6ngud9/0cEOE/8DTwxn8ZEMQLlAKTnCYmVEL11F6gY9vaymnujYqik2yaMo0tTFQl+njpD6OoabV3J8DiGLbMb348eNHYeAAVvfmMgxbHJyBzlOTTQNVEr4TBnFvYpSq5/8E5uRYdOZz5h00NtAdaJCkWP62QGVjSXjHelLo1WkmD/TemvezTicBzenjBj2ssZInvZ7DU5URapbcURrjTQiQevJfbO4bromuLSpW1+IwMx3R1QjORPS8tbOl60LstG5YJfKW1PMq9IylOEFtw1gbyfeyv9iPIEVMYACtr87oVZ77CkfYfvI4Wie6DAM4kjuHXyLUH4DTgKh/vOjXdt6/1+Hkb2yI=
    admin-user: AgC9QQZgH7g09/Oy+Vjf9GGazQs7ujot7lT0ZnUPys/Dn1uXUisdBEF1o+dtFqI/x5+6JhcD9hJVtjzO7ASOMF8sP4WC4L7UPIL4hXrI69HeELZ60DfV0m0A1Rbfubo7aga8+K56/6g9TsdyWcF670KOZAn5DpJUoYe8XsExnWKwxEMu6JXgY2GRYuNJ6SlkqOCeGaR4A4kRmZc3+/gwJWNxnLqkV/QuJdfhGUs4tfkUq7hB79TY1hFRrj8soXabDr9wcASRpvFwyFmfoUwRy9KV0vWjmu6et47vTAXoQcT7cayNZ0/mMeYrmRCiy9A0HnHQQNwpbK/GIcHPszSK0gnV6Bh7a3C9XXBshA++1aarARO4CTt3bjSkooX+M3LaneS4G23XDA+WInXp0OZIhFVYh5H0+hlVM1vdFFZmqpiYCva4lp6HWgdveCVi7X14C041HsjXqaBIeDVkJ2v2r5W7yFEZVguRH7BhOyNmTY7QRD1oiK1dKSw3/hQ+U5cd9mrAbcFeefPkekm2VZYqVxodAqjG+SxDDqoB/SW2X6vkJ9jhcc49broKPOFvXqaP4ei3xFKd7dG7JRsJFtvQrQj/D16z6C5bkumhlA13kK8s4x80A0yHa0J3pdZ4ljhea/SwLf7AaSBkeYZhwTLydzWUHxtgENaAhHdpnXt/qRcC7eIIL+IZwdP579XBGhXqnG2jN3zQ7Q==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
