---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth-keycloak-creds
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgCkuyu2MEiNUJcvhEfNwrrmpZTs1kpGqOo4ynNG/oftUwjdR7aNH5xEgWiGH1kbxxxUkwLBHCT/3FrbkkPEd2ZgNh/3wEyMotUGEiC0/MeO2ag/L9NGgpcV+5NWs5R9q+m/xLGHCp0KgSNcjRHpQgv+jlZ3xRa+jxVgjWy8ZDHOQCMTG9vOQnQPC5t63TGZMolv3nQRlIO0XVS6oJS25i67xJC2LiX8EEkzTC2tqS8VwLk0Z8A1MU8xgG2mViRYXyuA5Wa37EWxZqmrJ7ZeXJcnxpZn1DYP47fIlZHkHo3QBd9/1clene30ntiVwpQM7HkepUEgt7lAR+vM28Q/NSU1IEjKbeiw0SMyRcMFvcY1fA4Jrm2dyiN9QE3du2f0vYSU77+VdlkFUKPOslkbYDxGHBGPSmGYNMTns1qRYbyk28uwzPOmodGZSqhAnUXRMSyrZcIRSSGXguDi4+tWle11nmBiBUfcj0wol+0h8cFpOKg6E6opzyXlrl0uzlcE6aER4bsBXJfZ718KVbZgu92nYJa4H9/FwLJqYJQxLrvdRBJeT3d3cCjbrUC7e7std9G0z7Pga3HFTSEAU+O52jfq5X6eTFukFCC4ZookjmSWFoONmz6496soC6XyydfskQ6uaaVFwNRokocIP2lkiCoL7s99XYJ1M21jelTlDdnt/Imup9GaKrY7MDSpv0wZWXVWYJ6oLFPs
    client_secret: AgC17kHWc/8z9ZNpTJYeweLnIiAU6gTQYP1TuzJsCd9xCWlVJ7amL8TNAjQRuKx8+aopfhof3ZQdfFdTD7ztNyjx7lxtszmMFnMBRTxeNoyvWOQjo39JF9wUVcrR7lRCHj03DzMYkUj5dExjbV6aC0MGNlvwUHsUpHnFTDBfuq4mVoZE6po+H4CrxKoqq+7rH08P28/wnPJRvwXhxiKTs6IRIH4FRc1cB6IfKYTOqtt07PC5KE/g6gaSCn6hYdKbXyJ+63/MpwALE1TUg5EVZcMVyynlTOUs59XMtjz25BUYTxikD23Lf9BdAxM0G5+wyWe6liBkGiig7SWAIsxKIBfWccKaB+BjdcyTLqlauEbKw5rfri8LhpThI0pRkRq5XExnFocHAXGXHwvjQtnecqoQ67b97xT3FJo4PwNXkNCJ9wQgwVTu/0ptyUKBmnhvNLBu30GAm12fbUruT0I6JodDNnmKOehUAosKcgcHO3SOXsS1GKetqPXuurCxQWB4i74xK/GRu+PI+Q9mkXinpcN8iIXLs6Q4gbHokRwhqoDnaVcWUzx8ZXdA0l2C/xEgEg1tJCbh3vaHMTWBLjqL3lntnzzEeyht29c6wiL1qVkdvaBlNhyfmz9uzTNK1+hOrKO8/sjw+nOZgMRkO/96pWNm+9E+djlL3KOo28qg0brKCvbcwiJQQRSU4EQ60iBKGMb1GDMHgrzsuIzZE/dnsh9+YLIPGQrVyg8VnaFwsAU4NQ==
  template:
    metadata:
      name: grafana-oauth-keycloak-creds
      namespace: monitoring
