apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: kube-system # Traefik listens to the store in its own namespace
spec:
  defaultCertificate:
    secretName: kube-tls