---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB57f7b5OJomSI9en1mAIakonIhKHVxbPhNGQ7VU6oZEy83p7+Y2/+sjeH/62D4fg1PBkDXa9Nkh7sOm/ddcBFi3GKueqWDNDH6SvrAuNub1M7cI2F4wnJ7SBQ8BhcCTEDlrypRPkgRuhaAjtHaRm2CrqXR3DR9qF4IaYC7rEHoYbVY3MPKRmJOVKac5H8OVzKF+IGYy9jplZLHOXIs1rsbGE7zSmOH+4IUE9wxyHyaDqlG3WsTIW5UL+FmxvCUwOEJtq4K9LDy8kU3fqPIRWZCJG6XgkvTHK7eEvBV2LY8vkluVlALfRwLwW1ChFLc/5x95I0UcxUTT/JMgbNxCfQTKhMJIYVAS6J+eAHit5j4Gnyb6Jtx36BeXLbYvezzPtCv8c1G5hDTftOqS47AssorgrTZAcWMoYaY+q7E+BkvVje2sljH0868TydzEd1Zku+FZ8BkW3f7S6MN9oapBZe5HqH9pFvvBJW9mI5gJVxPqZpgQFZJuB6UwnHKK3/VFiNfnIEissNahDO5TxGHdKFvOSumyvobrCQbtLls6QO9pFQhorm2nVRpXLws5LP4jQq1n0oFno/isqsQ6yqlCUu1D1VCMlovhCB3folxrEzEcU/rB3rRO7ojWWoK88DViNfV1f4Oi/M1w764iWJfo6F2o5wyGAmzuklXCt0CWmai97/0dcE04X6D67pZsVpOuetJUgQb6UUfIc8oPVzlsRehPA==
    admin-user: AgC9C80YlSpUsFFfRRNQ987bhlpy+9C99dlSPpbervt1G83RO2ImMn3sDWcTbpEaEnWbBu4Neg6QknIPQwlV0eXXn/CtJOG2T5gsc6NJNMC2SwL/CktqNA7ip7VtfAwDkj1UgPek4GKyggANRg9PKRJKhzafal6JO0PHD6I2E01y+4cHRs6c6tbO23jhpuC/6mYm0JZI/x6B1PbMPzSFCUjsD5PMkX94OdtS5fhdNHV4ToAzy1VBngAKkgYUgIUHAfr+yiwruNJfAVmckAwbU6PmRczIyLJiPl7itdkiSmrIncBfUSInlW6LyRzDiquXeTTw15hW2JlH0g95/8uZbGEI3VWpalqyz1MSTxHNV+miCgbNjpFXu8WWuzDsCPnQ6cfUieJh982LT9uXyHxyyJNih+54PtaMOi6yAfOurCJqYXFDlxvR7vF8X31pBA01xfOXkYOnykFB6FVuTrQg55R9nXMgUlW0qfUfApR9SED678mfPZxC4RzuQiJdeXhatKvOIpcuEB21s+KX54QAPnFCvJ1T7TKo4GHWovGY/EgqQpFzxetQz0BX4gsuw6hyiog+89HW0vHcB0l4DJGTi8R/4cN9OlqP8qcZ88JSxQ7osPW9RNxmpts/Doqmjks8RTlXjyYNjX/taf1SW7rie3vNhi2N65bQMxsDjUmFyXUrVMqF4TUPcHoWtgj57fBlejSyvQLcUA==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
