apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Tell Kustomize to render this chart
helmCharts:
  - name: sealed-secrets
    # The official Helm Repo URL
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.18.0
    releaseName: sealed-secrets-controller
    namespace: auth
    # Point to your local values file
    valuesFile: values.yaml
    # Important: Include CRDs if this is a fresh install
    includeCRDs: true