apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - sealed-keycloak-admin-creds.yaml
  - ingress-route.yaml

helmCharts:
  - name: keycloakx
    repo: oci://ghcr.io/codecentric/helm-charts
    version: 7.1.7 # Corresponds to Keycloak ~26.5.1
    releaseName: auth-keycloak
    namespace: auth
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml