apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 28.6.0
    releaseName: mon-prometheus
    namespace: monitoring
    valuesFile: ../../base/values.yaml