apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../platform/monitoring/alloy
  - ../../../../platform/monitoring/grafana/overlays/df-test
  - ../../../../platform/monitoring/loki/overlays/df-test
  - ../../../../platform/monitoring/prometheus/overlays/df-test
  - ../../../../platform/monitoring/tempo/overlays/df-test
  - certificate.yaml
