apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

# Import the Sealed Secret here so the DB can find it
resources:
  - sealed-keycloak-pg-creds.yaml

helmCharts:
  - name: postgres
    repo: oci://registry-1.docker.io/cloudpirates
    version: 0.14.1
    releaseName: auth-postgres
    namespace: auth
    valuesFile: ../../base/values.yaml