apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-mon-creds.yaml

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.49.0
    releaseName: mon-loki
    namespace: monitoring
    valuesFile: ../../base/values.yaml
    # We don't need extra values for local, the base covers it