---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBuMyAYY5th/oTGwaqYvIMntSIGLZccBfT1zLy2oEpgBT4ASh9tMKyl639vUCfftGWhfBs4UNhSKEOfzm+N4AnjGhrda36kaLsFrkNBXffGL25x2H4d20TfhaCToWUqD2sFu3izCWgcYqH/keh3o6+bmNcoBFR9icNrZMwjZcoe/SM516AJ5RqWkB6NNOPkutAGY0XtceUgM0WJdiTWO+VxVbkZtF7wAZ2cbd+EnQQfdMKOwtBcAPlkTZWtktJM87/q9murMuU+/f6UWRURhtszQcWwZjUWs6OjsrnLKN6zHRMWNHkdkTkCyTzbavaw26B34JSfnddv92j+KbjgwxKWRSTYDnkRHYOJlmR/Od3x677hBG5O+weXFstNUPy3a2+rY9uA1ioMKiH7VUskMrOOyVBaEFj8LryZXjYFnQANkr/a5DxDRgVDbU1NQ7oVpknuhNxKkNezNP6lXdxKIOpHzw1wKNdl614hTjhK+GmzEQVmHy2BR/9/KwL27nTNoZUumncaGeiAinLYPZMjvWA/tMUUDdh0Fbh4+Gh7nUfbPk/ZXjr1tl4NwFZCV2sz60pyyLS03UVWCikf8G6Y21+BNAC9SRs0rHnmVDksbNHchm/LPyWuv7yhMMUpiPYHt/28zJ72u+uABsJZ+Foz7dHiSr8MSfigcgAaEe/t0mgZxOP8P750oFz8ZuupTTWR58A4arXSNQKQKi6o05wOLClkaQ==
    admin-user: AgChLVviN8BzF46KlckBCq90E9fHOpWjCqxYmzSMiOWTd9Fx0r2FzD3FkVOGxvYz2dBi072uvIpHqIRzJre0H0y/OYFsymyyXc1xGwLuFqJ3Z8XsfRwpXKnjTOo5x4tMnKTw5eMaNBeuAqf0XLYbKv+ew2COrDOWQoCdaLUESWPm5TMzRqkEqA4kn1gTkPfo2U50YCh/vOY4g36PrT0KbM0ReUJv1hfrbOAINxDvRwRkTAdQoyf6znzGRe07mIQEqUhCE3C4AvmJpZe9D9Jo97dYEOM1T0/QFYzrwzGLtvy3nrwcYwbxinZW/oAEDLi6IqE/pMa5S5XxsjNk2GowJ3IyN0W/mo6Or5L3xPyZaguB9cTyR/OyU0KBbJazWVMPZICdRjpvIrzSIMNtHbl3M3CMrHLnEXcqyqht1t4W578YpR05Y1GV8Qqr+a90d0Ah/nVEp1Tc+b0Bk89R2Vn9iK9ZE80YF/jEItcKg+GxTyD0IfzuVwvK7SqJV/n1Ao4leATFZSTaj1AKLuiQhk5fDolpMZmfxodHE1ZPYILO4lpKhQkX+JJBwY9P0RXmgFChPO6LXangx+sLmW/2lOsNIBxlO6n6KtJ1J+nT7XEW2TkysZzvpuQTCSWqLlCeOJGAJZZ6Vq/PDV6hhBBzPwkYLAer1J4KVYp/93d+BSOAdqY8MOkBScPf/9OIQE98vE8DCfQcp9Al6g==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
