apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../platform/auth/db/overlays/bp-dsk
  - ../../../../platform/auth/keycloak/overlays/bp-dsk
  - certificate.yaml
