apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../platform/auth/sealed-secrets/
  - ../../../../platform/auth/cert-manager/
  - ../../../../platform/auth/db/overlays/df-test
  - ../../../../platform/auth/keycloak/overlays/df-test
  - certificate.yaml
